{
  "openapi": "3.0.3",
  "info": {
    "title": "Main API",
    "description": "Public facing API to manage all my project features",
    "version": "1.0.0",
    "contact": {}
  },
  "servers": [{ "url": "{{base_url}}" }],
  "paths": {
    "/": {
      "get": {
        "tags": ["Home"],
        "summary": "Ping server",
        "description": "Ping server",
        "operationId": "pingServer",
        "responses": {
          "200": {
            "description": "200 - Ping server",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb6254da23fd63-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "close" }
              },
              "Content-Encoding": {
                "schema": { "type": "string", "example": "br" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:39:44 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"25-xRq02FWva4DiUm8AOw8+nS+TtZ0\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=dyO1qk4RhxgYVPo1aQXXK%2FP%2B%2BZ%2FlidVoHM54o0xB1TgDbS3oPseVv4wH1ORnqkDbQKBHvUAvou5Hgnxm7weEtU8ZvUshYcrOrBPhb8cNBn7E\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Transfer-Encoding": {
                "schema": { "type": "string", "example": "chunked" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "79d5116247f1de1bb370a1e05c08e36d;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "documentationUrl": {
                          "type": "string",
                          "example": "https://api.ccrsxx.com/docs"
                        },
                        "message": {
                          "type": "string",
                          "example": "Welcome! The API is up and running"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "200 - Ping server": {
                    "value": {
                      "data": {
                        "documentationUrl": "https://api.ccrsxx.com/docs",
                        "message": "Welcome! The API is up and running"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sse": {
      "get": {
        "tags": ["SSE"],
        "summary": "Get sse events",
        "description": "Get currently playing track on Spotify with Server Sent Events",
        "operationId": "getSseEvents",
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "schema": { "type": "string", "example": "{{secret_key}}" }
          }
        ],
        "responses": {
          "200": {
            "description": "200 - Get sse events",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Cache-Control": {
                "schema": { "type": "string", "example": "no-cache" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 20 Jul 2025 01:34:03 GMT"
                }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "10" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "10;w=10" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "9" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "10" }
              },
              "Transfer-Encoding": {
                "schema": { "type": "string", "example": "chunked" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "text/plain": {
                "examples": {
                  "200 - Get sse events": {
                    "value": "data: {\"data\":{\"message\":\"Connection established. Waiting for updates...\"}}\n\nevent: spotify\ndata: {\"data\":{\"platform:\"spotify\",\"isPlaying\":true,\"item\":{\"trackUrl\":\"https://open.spotify.com/track/1rteFRVH1opcZCYLO6qwZx\",\"trackName\":\"Ëä±„ÅÆ„Çà„ÅÜ„Å´\",\"albumName\":\"„Ç¢„É´„Çπ„Éà„É≠„É°„É™„Ç¢\",\"artistName\":\"Anna\",\"progressMs\":114639,\"durationMs\":250186,\"albumImageUrl\":\"https://i.scdn.co/image/ab67616d0000b2738f1ff2420518ea5bcf51c22a\"}}}\n\nevent: jellyfin\ndata: {\"data\":{\"platform:\"jellyfin\",\"isPlaying\":true,\"item\":{\"trackUrl\":null,\"trackName\":\"Ëä±„ÅÆ„Çà„ÅÜ„Å´\",\"albumName\":\"„Ç¢„É´„Çπ„Éà„É≠„É°„É™„Ç¢\",\"artistName\":\"Anna\",\"progressMs\":114639,\"durationMs\":250186,\"albumImageUrl\":\"https://i.scdn.co/image/ab67616d0000b2738f1ff2420518ea5bcf51c22a\"}}}\n"
                  }
                }
              }
            }
          },
          "401": {
            "description": "401 - Invalid token",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb79e3bf0a40d8-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "94" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:55:47 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5e-/VC2Pm+Z/HQceaX/TadZBqXZInk\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=pC06wzVVDzSgIWvUjuu0dZyOODYmRYAAYyrLwm8C3lJNkEZCuUwvLwghP%2FI0xWTJbOL8xqnF%2F6oEbsXxJAvSD6hPkZDoZyZZPLcYnvg9BAeS\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "6e544d066e649407d4118ac0bf839510;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e"
                        },
                        "message": {
                          "type": "string",
                          "example": "Invalid token"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "401 - Invalid token": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e",
                        "message": "Invalid token"
                      }
                    }
                  }
                }
              }
            }
          },
          "429": {
            "description": "429 - Maximum number of clients for your IP reached",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "144" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 18 Jul 2025 17:12:49 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"90-Yy7oBrX6Utz/Kd11gtO26lRva5k\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "98" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "57" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "1af1395d-f785-4a0b-b12d-281a7483a531"
                        },
                        "message": {
                          "type": "string",
                          "example": "Maximum number of clients for your IP reached. Try again later."
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "429 - Maximum number of clients for your IP reached": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "1af1395d-f785-4a0b-b12d-281a7483a531",
                        "message": "Maximum number of clients for your IP reached. Try again later."
                      }
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "503 - Maximum number of clients reached",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "132" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 18 Jul 2025 17:11:51 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"84-qWWEwPW7bsXHdpYzq+tAPnPu+7Y\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "98" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "55" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "bb5ee099-248d-4d83-842c-374a793651a4"
                        },
                        "message": {
                          "type": "string",
                          "example": "Maximum number of clients reached. Try again later."
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "503 - Maximum number of clients reached": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "bb5ee099-248d-4d83-842c-374a793651a4",
                        "message": "Maximum number of clients reached. Try again later."
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tools/ip": {
      "get": {
        "tags": ["Tools"],
        "summary": "Get IP addresss",
        "description": "Get IP addresss",
        "operationId": "getIpAddresss",
        "responses": {
          "200": {
            "description": "200 - Get IP address",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "34" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Oct 2025 18:53:33 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"22-Z4Wmsoc38oRdyAg2B/KUclpZzIU\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "99" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "60" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "text/plain": {
                "examples": { "200 - Get IP address": { "value": "1.1.1.1" } }
              }
            }
          }
        }
      }
    },
    "/tools/ipinfo": {
      "get": {
        "tags": ["Tools"],
        "summary": "Get IP address info",
        "description": "Get IP address info",
        "operationId": "getIpAddressInfo",
        "responses": {
          "200": {
            "description": "200 - Get IP address info",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "34" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Oct 2025 18:53:33 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"22-Z4Wmsoc38oRdyAg2B/KUclpZzIU\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "99" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "60" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "anycast": { "type": "boolean", "example": true },
                        "city": { "type": "string", "example": "Brisbane" },
                        "continent": {
                          "type": "object",
                          "properties": {
                            "code": { "type": "string", "example": "OC" },
                            "name": { "type": "string", "example": "Oceania" }
                          }
                        },
                        "country": { "type": "string", "example": "Australia" },
                        "countryCode": { "type": "string", "example": "AU" },
                        "countryCurrency": {
                          "type": "object",
                          "properties": {
                            "code": { "type": "string", "example": "AUD" },
                            "symbol": { "type": "string", "example": "$" }
                          }
                        },
                        "countryFlag": {
                          "type": "object",
                          "properties": {
                            "emoji": { "type": "string", "example": "üá¶üá∫" },
                            "unicode": {
                              "type": "string",
                              "example": "U+1F1E6 U+1F1FA"
                            }
                          }
                        },
                        "countryFlagURL": {
                          "type": "string",
                          "example": "https://cdn.ipinfo.io/static/images/countries-flags/AU.svg"
                        },
                        "hostname": {
                          "type": "string",
                          "example": "one.one.one.one"
                        },
                        "ip": { "type": "string", "example": "1.1.1.1" },
                        "isEU": { "type": "boolean", "example": false },
                        "loc": {
                          "type": "string",
                          "example": "-27.4816,153.0175"
                        },
                        "org": {
                          "type": "string",
                          "example": "AS13335 Cloudflare, Inc."
                        },
                        "postal": { "type": "string", "example": "4101" },
                        "region": { "type": "string", "example": "Queensland" },
                        "timezone": {
                          "type": "string",
                          "example": "Australia/Brisbane"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "200 - Get IP address info": {
                    "value": {
                      "data": {
                        "anycast": true,
                        "city": "Brisbane",
                        "continent": { "code": "OC", "name": "Oceania" },
                        "country": "Australia",
                        "countryCode": "AU",
                        "countryCurrency": { "code": "AUD", "symbol": "$" },
                        "countryFlag": {
                          "emoji": "üá¶üá∫",
                          "unicode": "U+1F1E6 U+1F1FA"
                        },
                        "countryFlagURL": "https://cdn.ipinfo.io/static/images/countries-flags/AU.svg",
                        "hostname": "one.one.one.one",
                        "ip": "1.1.1.1",
                        "isEU": false,
                        "loc": "-27.4816,153.0175",
                        "org": "AS13335 Cloudflare, Inc.",
                        "postal": "4101",
                        "region": "Queensland",
                        "timezone": "Australia/Brisbane"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400 - Invalid query",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "94" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 19 Oct 2025 09:37:50 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5e-k2uj15l/CPfj41jZHqCv+h7k9Nw\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "98" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "55" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "6b2612ce-4841-4c21-a02a-6a19231d385a"
                        },
                        "message": {
                          "type": "string",
                          "example": "Invalid input"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "400 - Invalid query": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "6b2612ce-4841-4c21-a02a-6a19231d385a",
                        "message": "Invalid input"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tools/headers": {
      "get": {
        "tags": ["Tools"],
        "summary": "Get request headers",
        "description": "Get request headers",
        "operationId": "getRequestHeaders",
        "responses": {
          "200": {
            "description": "200 - Get request headers",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "205" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Oct 2025 19:23:44 GMT"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"cd-SYW1jOKjUY5EXv8b/tI9dwuDhug\""
                }
              },
              "Keep-Alive": {
                "schema": { "type": "string", "example": "timeout=5" }
              },
              "RateLimit-Limit": {
                "schema": { "type": "string", "example": "100" }
              },
              "RateLimit-Policy": {
                "schema": { "type": "string", "example": "100;w=60" }
              },
              "RateLimit-Remaining": {
                "schema": { "type": "string", "example": "99" }
              },
              "RateLimit-Reset": {
                "schema": { "type": "string", "example": "60" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "accept": {
                          "type": "string",
                          "example": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        },
                        "accept-encoding": {
                          "type": "string",
                          "example": "gzip, br"
                        },
                        "accept-language": {
                          "type": "string",
                          "example": "en-GB"
                        },
                        "cdn-loop": {
                          "type": "string",
                          "example": "cloudflare; loops=1"
                        },
                        "cf-access-jwt-assertion": {
                          "type": "string",
                          "example": "x"
                        },
                        "cf-connecting-ip": {
                          "type": "string",
                          "example": "1.1.1.1"
                        },
                        "cf-ipcountry": { "type": "string", "example": "ID" },
                        "cf-ray": { "type": "string", "example": "x-SIN" },
                        "cf-visitor": {
                          "type": "string",
                          "example": "{\"scheme\":\"https\"}"
                        },
                        "cf-warp-tag-id": { "type": "string", "example": "x" },
                        "connection": {
                          "type": "string",
                          "example": "keep-alive"
                        },
                        "cookie": { "type": "string", "example": "x" },
                        "host": {
                          "type": "string",
                          "example": "api.ccrsxx.com"
                        },
                        "priority": { "type": "string", "example": "u=0, i" },
                        "sec-fetch-dest": {
                          "type": "string",
                          "example": "document"
                        },
                        "sec-fetch-mode": {
                          "type": "string",
                          "example": "navigate"
                        },
                        "sec-fetch-site": {
                          "type": "string",
                          "example": "none"
                        },
                        "sec-fetch-user": { "type": "string", "example": "?1" },
                        "sec-gpc": { "type": "string", "example": "1" },
                        "upgrade-insecure-requests": {
                          "type": "string",
                          "example": "1"
                        },
                        "user-agent": {
                          "type": "string",
                          "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0"
                        },
                        "x-forwarded-for": {
                          "type": "string",
                          "example": "1.1.1.1"
                        },
                        "x-forwarded-proto": {
                          "type": "string",
                          "example": "https"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "200 - Get request headers": {
                    "value": {
                      "data": {
                        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                        "accept-encoding": "gzip, br",
                        "accept-language": "en-GB",
                        "cdn-loop": "cloudflare; loops=1",
                        "cf-access-jwt-assertion": "x",
                        "cf-connecting-ip": "1.1.1.1",
                        "cf-ipcountry": "ID",
                        "cf-ray": "x-SIN",
                        "cf-visitor": "{\"scheme\":\"https\"}",
                        "cf-warp-tag-id": "x",
                        "connection": "keep-alive",
                        "cookie": "x",
                        "host": "api.ccrsxx.com",
                        "priority": "u=0, i",
                        "sec-fetch-dest": "document",
                        "sec-fetch-mode": "navigate",
                        "sec-fetch-site": "none",
                        "sec-fetch-user": "?1",
                        "sec-gpc": "1",
                        "upgrade-insecure-requests": "1",
                        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0",
                        "x-forwarded-for": "1.1.1.1",
                        "x-forwarded-proto": "https"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/spotify/currently-playing": {
      "get": {
        "tags": ["Spotify"],
        "summary": "Get currently playing",
        "description": "Get currently playing track on Spotify",
        "operationId": "getCurrentlyPlaying",
        "responses": {
          "200": {
            "description": "200 - Get currently playing",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb7a5f8be440d8-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Encoding": {
                "schema": { "type": "string", "example": "br" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:56:08 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"199-FhWc+f64DAV5Sda5bOqYSmbWMeE\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=9aePbhRUHqkh8cn9J4614KeB3fosVeExqEgu2ysCEXlXtvhyoaScCQHOCoe3VfrKc7COu%2F%2FkTN2KOqBa6pvYRbU1nvaP9dqpTABY5INM1JDe\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Transfer-Encoding": {
                "schema": { "type": "string", "example": "chunked" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "26c235279f06a9c13095b0e9747c5b4d;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "isPlaying": { "type": "boolean", "example": true },
                        "item": {
                          "type": "object",
                          "properties": {
                            "albumImageUrl": {
                              "type": "string",
                              "example": "https://i.scdn.co/image/ab67616d0000b273d1a9be7be47701c762ed0dda"
                            },
                            "albumName": {
                              "type": "string",
                              "example": "ÊÅãÈ¢®"
                            },
                            "artistName": {
                              "type": "string",
                              "example": "Lilas"
                            },
                            "durationMs": {
                              "type": "number",
                              "example": 182029
                            },
                            "progressMs": {
                              "type": "number",
                              "example": 25882
                            },
                            "trackName": {
                              "type": "string",
                              "example": "ÊÅãÈ¢®"
                            },
                            "trackUrl": {
                              "type": "string",
                              "example": "https://open.spotify.com/track/6QGuDk8tY8Lan39gTWtXWK"
                            }
                          }
                        },
                        "platform": { "type": "string", "example": "spotify" }
                      }
                    }
                  }
                },
                "examples": {
                  "200 - Get currently playing": {
                    "value": {
                      "data": {
                        "isPlaying": true,
                        "item": {
                          "albumImageUrl": "https://i.scdn.co/image/ab67616d0000b273d1a9be7be47701c762ed0dda",
                          "albumName": "ÊÅãÈ¢®",
                          "artistName": "Lilas",
                          "durationMs": 182029,
                          "progressMs": 25882,
                          "trackName": "ÊÅãÈ¢®",
                          "trackUrl": "https://open.spotify.com/track/6QGuDk8tY8Lan39gTWtXWK"
                        },
                        "platform": "spotify"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401 - Invalid token",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb79e3bf0a40d8-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "94" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:55:47 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5e-/VC2Pm+Z/HQceaX/TadZBqXZInk\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=pC06wzVVDzSgIWvUjuu0dZyOODYmRYAAYyrLwm8C3lJNkEZCuUwvLwghP%2FI0xWTJbOL8xqnF%2F6oEbsXxJAvSD6hPkZDoZyZZPLcYnvg9BAeS\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "6e544d066e649407d4118ac0bf839510;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e"
                        },
                        "message": {
                          "type": "string",
                          "example": "Invalid token"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "401 - Invalid token": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e",
                        "message": "Invalid token"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": [{ "bearerAuth": [] }]
      }
    },
    "/jellyfin/currently-playing": {
      "get": {
        "tags": ["Jellyfin"],
        "summary": "Get currently playing",
        "description": "Get currently playing track on Spotify",
        "operationId": "getCurrentlyPlaying1",
        "responses": {
          "200": {
            "description": "200 - Get currently playing",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb7a5f8be440d8-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Encoding": {
                "schema": { "type": "string", "example": "br" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:56:08 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"199-FhWc+f64DAV5Sda5bOqYSmbWMeE\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=9aePbhRUHqkh8cn9J4614KeB3fosVeExqEgu2ysCEXlXtvhyoaScCQHOCoe3VfrKc7COu%2F%2FkTN2KOqBa6pvYRbU1nvaP9dqpTABY5INM1JDe\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Transfer-Encoding": {
                "schema": { "type": "string", "example": "chunked" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "26c235279f06a9c13095b0e9747c5b4d;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "isPlaying": { "type": "boolean", "example": true },
                        "item": {
                          "type": "object",
                          "properties": {
                            "albumImageUrl": {
                              "type": "string",
                              "example": "https://i.scdn.co/image/ab67616d0000b273d1a9be7be47701c762ed0dda"
                            },
                            "albumName": {
                              "type": "string",
                              "example": "ÊÅãÈ¢®"
                            },
                            "artistName": {
                              "type": "string",
                              "example": "Lilas"
                            },
                            "durationMs": {
                              "type": "number",
                              "example": 182029
                            },
                            "progressMs": {
                              "type": "number",
                              "example": 25882
                            },
                            "trackName": {
                              "type": "string",
                              "example": "ÊÅãÈ¢®"
                            },
                            "trackUrl": { "nullable": true, "example": null }
                          }
                        },
                        "platform": { "type": "string", "example": "jellyfin" }
                      }
                    }
                  }
                },
                "examples": {
                  "200 - Get currently playing": {
                    "value": {
                      "data": {
                        "isPlaying": true,
                        "item": {
                          "albumImageUrl": "https://i.scdn.co/image/ab67616d0000b273d1a9be7be47701c762ed0dda",
                          "albumName": "ÊÅãÈ¢®",
                          "artistName": "Lilas",
                          "durationMs": 182029,
                          "progressMs": 25882,
                          "trackName": "ÊÅãÈ¢®",
                          "trackUrl": null
                        },
                        "platform": "jellyfin"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401 - Invalid token",
            "headers": {
              "Access-Control-Allow-Credentials": {
                "schema": { "type": "string", "example": "true" }
              },
              "CF-RAY": {
                "schema": {
                  "type": "string",
                  "example": "95fb79e3bf0a40d8-SIN"
                }
              },
              "Cf-Cache-Status": {
                "schema": { "type": "string", "example": "DYNAMIC" }
              },
              "Connection": {
                "schema": { "type": "string", "example": "keep-alive" }
              },
              "Content-Length": {
                "schema": { "type": "string", "example": "94" }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 15 Jul 2025 18:55:47 GMT"
                }
              },
              "Etag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5e-/VC2Pm+Z/HQceaX/TadZBqXZInk\""
                }
              },
              "Nel": {
                "schema": {
                  "type": "string",
                  "example": "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
                }
              },
              "Report-To": {
                "schema": {
                  "type": "string",
                  "example": "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=pC06wzVVDzSgIWvUjuu0dZyOODYmRYAAYyrLwm8C3lJNkEZCuUwvLwghP%2FI0xWTJbOL8xqnF%2F6oEbsXxJAvSD6hPkZDoZyZZPLcYnvg9BAeS\"}]}"
                }
              },
              "Server": {
                "schema": { "type": "string", "example": "cloudflare" }
              },
              "Vary": { "schema": { "type": "string", "example": "Origin" } },
              "X-Cloud-Trace-Context": {
                "schema": {
                  "type": "string",
                  "example": "6e544d066e649407d4118ac0bf839510;o=1"
                }
              },
              "X-Powered-By": {
                "schema": { "type": "string", "example": "Express" }
              },
              "alt-svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=86400"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "details": {
                          "type": "array",
                          "items": {},
                          "example": []
                        },
                        "id": {
                          "type": "string",
                          "example": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e"
                        },
                        "message": {
                          "type": "string",
                          "example": "Invalid token"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "401 - Invalid token": {
                    "value": {
                      "error": {
                        "details": [],
                        "id": "c4971b49-7ce5-42d4-9045-311f7f5e2e7e",
                        "message": "Invalid token"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": [{ "bearerAuth": [] }]
      }
    },
    "/og": {
      "get": {
        "tags": ["Open Graph Image"],
        "summary": "Get open graph image",
        "description": "Get open graph image",
        "operationId": "getOpenGraphImage",
        "parameters": [
          {
            "name": "title",
            "in": "query",
            "schema": {
              "type": "string",
              "example": "Data Fetching in Next.js"
            }
          },
          {
            "name": "description",
            "in": "query",
            "schema": {
              "type": "string",
              "example": "Learn about the different methods for fetching data in Next.js, including static generation, server-side rendering, and client-side rendering."
            }
          },
          {
            "name": "type",
            "in": "query",
            "schema": { "type": "string", "example": "blog" }
          },
          {
            "name": "article",
            "in": "query",
            "schema": { "type": "string", "example": "true" }
          },
          {
            "name": "image",
            "in": "query",
            "schema": {
              "type": "string",
              "example": "https://risalamin.com/_next/static/media/banner.4d6606be.jpg"
            }
          }
        ],
        "responses": { "200": { "description": "" } }
      }
    }
  },
  "components": {
    "securitySchemes": { "bearerAuth": { "type": "http", "scheme": "bearer" } }
  },
  "tags": [
    { "name": "Home" },
    { "name": "SSE" },
    { "name": "Tools" },
    { "name": "Spotify" },
    { "name": "Jellyfin" },
    { "name": "Open Graph Image" }
  ]
}
